import React, { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { Screen, AppHeader, Button, FormModal, IconBadge, ProgressBar, SectionTitle, EmptyState } from '@/components/FinanceUI';
import { formatMoney, useFinance } from '@/store/FinanceContext';

export default function DebtsScreen() {
  const router = useRouter(); const { state, colors, addDebt, updateDebtPaid } = useFinance(); const [showForm, setShowForm] = useState(false); const currency = state.settings.currency;
  return <Screen><AppHeader title="الديون" subtitle="التزاماتك المالية القادمة" onBack={() => router.back()} action={() => setShowForm(true)} /><View style={[styles.summary, { backgroundColor: `${colors.destructive}12`, borderColor: `${colors.destructive}30` }]}><IconBadge icon="calendar-alert" color={colors.destructive} size={45} /><View style={styles.info}><Text style={[styles.label, { color: colors.mutedForeground }]}>إجمالي المتبقي</Text><Text style={[styles.value, { color: colors.destructive }]}>{formatMoney(state.debts.reduce((sum, d) => sum + d.amount - d.paid, 0), currency)}</Text></View></View><SectionTitle title="قائمة الديون" />{state.debts.length === 0 ? <EmptyState icon="calendar-check-outline" title="لا توجد ديون" description="ممتاز! لا توجد التزامات مالية مسجلة حالياً." onPress={() => setShowForm(true)} action="إضافة دين" /> : state.debts.map(debt => { const progress = debt.paid / debt.amount * 100; return <View key={debt.id} style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={styles.cardTop}><Text style={[styles.remaining, { color: colors.destructive }]}>{formatMoney(debt.amount - debt.paid, currency)}</Text><View style={styles.info}><Text style={[styles.name, { color: colors.foreground }]}>{debt.name}</Text><Text style={[styles.date, { color: colors.mutedForeground }]}>تاريخ الاستحقاق: {debt.dueDate}</Text></View><IconBadge icon="arrow-up-circle-outline" color={colors.destructive} size={42} /></View><ProgressBar progress={progress} color={colors.destructive} /><View style={styles.progressText}><Text style={[styles.tiny, { color: colors.mutedForeground }]}>مدفوع {formatMoney(debt.paid, currency)}</Text><Pressable onPress={() => updateDebtPaid(debt.id, debt.amount)}><Text style={[styles.pay, { color: colors.primary }]}>{progress >= 100 ? 'تم السداد' : 'تسجيل السداد'}</Text></Pressable></View></View> })}<FormModal visible={showForm} title="إضافة دين" onClose={() => setShowForm(false)} onSubmit={values => addDebt({ name: values.name, amount: Number(values.amount), paid: 0, dueDate: values.dueDate, note: values.note })} fields={[{ key: 'name', label: 'اسم الدين', placeholder: 'مثال: إيجار المنزل' }, { key: 'amount', label: 'المبلغ الإجمالي', placeholder: '0', keyboardType: 'decimal-pad' }, { key: 'dueDate', label: 'تاريخ الاستحقاق', placeholder: '2026-08-30' }, { key: 'note', label: 'ملاحظة', placeholder: 'تفاصيل إضافية' }]} /></Screen>;
}
const styles = StyleSheet.create({ summary: { flexDirection: 'row-reverse', alignItems: 'center', gap: 12, borderWidth: 1, borderRadius: 20, padding: 16 }, info: { flex: 1, alignItems: 'flex-end' }, label: { fontFamily: 'Inter_500Medium', fontSize: 12 }, value: { fontFamily: 'Inter_700Bold', fontSize: 22, marginTop: 5 }, card: { borderWidth: 1, borderRadius: 20, padding: 15, marginBottom: 10 }, cardTop: { flexDirection: 'row-reverse', alignItems: 'center', gap: 10, marginBottom: 14 }, name: { fontFamily: 'Inter_700Bold', fontSize: 14 }, date: { fontFamily: 'Inter_400Regular', fontSize: 11, marginTop: 4 }, remaining: { fontFamily: 'Inter_700Bold', fontSize: 13, maxWidth: 95, textAlign: 'left' }, progressText: { flexDirection: 'row-reverse', justifyContent: 'space-between', marginTop: 9 }, tiny: { fontFamily: 'Inter_400Regular', fontSize: 11 }, pay: { fontFamily: 'Inter_700Bold', fontSize: 11 } });