import React, { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { Screen, AppHeader, FormModal, IconBadge, ProgressBar, SectionTitle, EmptyState } from '@/components/FinanceUI';
import { formatMoney, useFinance } from '@/store/FinanceContext';

export default function GoalsScreen() {
  const router = useRouter(); const { state, colors, addGoal, updateGoalSaved } = useFinance(); const [showForm, setShowForm] = useState(false); const currency = state.settings.currency;
  return <Screen><AppHeader title="الأهداف المالية" subtitle="خطوات صغيرة نحو ما تريد" onBack={() => router.back()} action={() => setShowForm(true)} /><View style={[styles.summary, { backgroundColor: colors.accent }]}><IconBadge icon="target" color={colors.accentForeground} size={45} /><View style={styles.info}><Text style={[styles.label, { color: colors.accentForeground }]}>متوسط الإنجاز</Text><Text style={[styles.value, { color: colors.foreground }]}>{Math.round(state.goals.length ? state.goals.reduce((sum, g) => sum + g.saved / g.target * 100, 0) / state.goals.length : 0)}%</Text></View></View><SectionTitle title="أهدافي" />{state.goals.length === 0 ? <EmptyState icon="flag-checkered" title="لا توجد أهداف" description="حدد هدفاً مالياً واضحاً واجعل ادخارك أكثر حماساً." onPress={() => setShowForm(true)} action="إضافة هدف" /> : state.goals.map(goal => { const progress = goal.saved / goal.target * 100; return <View key={goal.id} style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={styles.top}><View style={styles.info}><Text style={[styles.name, { color: colors.foreground }]}>{goal.name}</Text><Text style={[styles.date, { color: colors.mutedForeground }]}>الموعد المستهدف: {goal.deadline}</Text></View><IconBadge icon={goal.status === 'completed' ? 'check-circle-outline' : 'flag-checkered'} color={goal.color} size={45} /></View><View style={styles.amounts}><Text style={[styles.saved, { color: goal.color }]}>{Math.round(progress)}%</Text><Text style={[styles.amountText, { color: colors.mutedForeground }]}>{formatMoney(goal.saved, currency)} من {formatMoney(goal.target, currency)}</Text></View><ProgressBar progress={progress} color={goal.color} /><Pressable onPress={() => updateGoalSaved(goal.id, goal.target)} style={styles.saveAction}><Text style={[styles.saveText, { color: colors.primary }]}>{goal.status === 'completed' ? 'تم إنجاز الهدف' : 'تسجيل ادخار كامل'}</Text></Pressable></View> })}<FormModal visible={showForm} title="إضافة هدف مالي" onClose={() => setShowForm(false)} onSubmit={values => addGoal({ name: values.name, target: Number(values.target), saved: Number(values.saved || 0), deadline: values.deadline, color: '#AE6DB0' })} fields={[{ key: 'name', label: 'اسم الهدف', placeholder: 'مثال: رحلة الشتاء' }, { key: 'target', label: 'المبلغ المستهدف', placeholder: '0', keyboardType: 'decimal-pad' }, { key: 'saved', label: 'المبلغ المدخر حالياً', placeholder: '0', keyboardType: 'decimal-pad' }, { key: 'deadline', label: 'التاريخ المستهدف', placeholder: '2026-12-31' }]} initialValues={{ saved: '0' }} /></Screen>;
}
const styles = StyleSheet.create({ summary: { flexDirection: 'row-reverse', alignItems: 'center', gap: 12, borderRadius: 20, padding: 16 }, info: { flex: 1, alignItems: 'flex-end' }, label: { fontFamily: 'Inter_500Medium', fontSize: 12 }, value: { fontFamily: 'Inter_700Bold', fontSize: 26, marginTop: 5, textAlign: 'right' }, card: { borderWidth: 1, borderRadius: 20, padding: 15, marginBottom: 10 }, top: { flexDirection: 'row-reverse', alignItems: 'center', gap: 10 }, name: { fontFamily: 'Inter_700Bold', fontSize: 15 }, date: { fontFamily: 'Inter_400Regular', fontSize: 11, marginTop: 4 }, amounts: { flexDirection: 'row-reverse', justifyContent: 'space-between', alignItems: 'center', marginVertical: 14 }, saved: { fontFamily: 'Inter_700Bold', fontSize: 15 }, amountText: { fontFamily: 'Inter_400Regular', fontSize: 11 }, saveAction: { alignItems: 'center', paddingTop: 11 }, saveText: { fontFamily: 'Inter_700Bold', fontSize: 12 } });