import React, { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { Screen, AppHeader, FormModal, IconBadge, ProgressBar, SectionTitle, EmptyState } from '@/components/FinanceUI';
import { formatMoney, useFinance } from '@/store/FinanceContext';

export default function LoansScreen() {
  const router = useRouter(); const { state, colors, addLoan, updateLoanReceived } = useFinance(); const [showForm, setShowForm] = useState(false); const currency = state.settings.currency;
  return <Screen><AppHeader title="القروض" subtitle="أموال لك لدى الآخرين" onBack={() => router.back()} action={() => setShowForm(true)} /><View style={[styles.summary, { backgroundColor: colors.secondary }]}><IconBadge icon="hand-coin-outline" color="#5578C8" size={45} /><View style={styles.info}><Text style={[styles.label, { color: colors.mutedForeground }]}>إجمالي المتبقي لك</Text><Text style={[styles.value, { color: colors.foreground }]}>{formatMoney(state.loans.reduce((sum, l) => sum + l.amount - l.received, 0), currency)}</Text></View></View><SectionTitle title="القروض المستحقة" />{state.loans.length === 0 ? <EmptyState icon="hand-coin-outline" title="لا توجد قروض" description="سجّل الأموال التي لك لدى الآخرين لمتابعتها بسهولة." onPress={() => setShowForm(true)} action="إضافة قرض" /> : state.loans.map(loan => { const progress = loan.received / loan.amount * 100; return <View key={loan.id} style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={styles.cardTop}><Text style={[styles.remaining, { color: '#5578C8' }]}>{formatMoney(loan.amount - loan.received, currency)}</Text><View style={styles.info}><Text style={[styles.name, { color: colors.foreground }]}>{loan.name}</Text><Text style={[styles.date, { color: colors.mutedForeground }]}>الاستحقاق: {loan.dueDate}</Text></View><IconBadge icon="arrow-down-circle-outline" color="#5578C8" size={42} /></View><ProgressBar progress={progress} color="#5578C8" /><View style={styles.progressText}><Text style={[styles.tiny, { color: colors.mutedForeground }]}>محصل {formatMoney(loan.received, currency)}</Text><Pressable onPress={() => updateLoanReceived(loan.id, loan.amount)}><Text style={[styles.pay, { color: colors.primary }]}>{progress >= 100 ? 'تم التحصيل' : 'تسجيل التحصيل'}</Text></Pressable></View></View> })}<FormModal visible={showForm} title="إضافة قرض" onClose={() => setShowForm(false)} onSubmit={values => addLoan({ name: values.name, amount: Number(values.amount), received: 0, dueDate: values.dueDate, note: values.note })} fields={[{ key: 'name', label: 'اسم المدين', placeholder: 'مثال: سلفة أحمد' }, { key: 'amount', label: 'المبلغ الإجمالي', placeholder: '0', keyboardType: 'decimal-pad' }, { key: 'dueDate', label: 'تاريخ الاستحقاق', placeholder: '2026-08-30' }, { key: 'note', label: 'ملاحظة', placeholder: 'تفاصيل إضافية' }]} /></Screen>;
}
const styles = StyleSheet.create({ summary: { flexDirection: 'row-reverse', alignItems: 'center', gap: 12, borderRadius: 20, padding: 16 }, info: { flex: 1, alignItems: 'flex-end' }, label: { fontFamily: 'Inter_500Medium', fontSize: 12 }, value: { fontFamily: 'Inter_700Bold', fontSize: 22, marginTop: 5 }, card: { borderWidth: 1, borderRadius: 20, padding: 15, marginBottom: 10 }, cardTop: { flexDirection: 'row-reverse', alignItems: 'center', gap: 10, marginBottom: 14 }, name: { fontFamily: 'Inter_700Bold', fontSize: 14 }, date: { fontFamily: 'Inter_400Regular', fontSize: 11, marginTop: 4 }, remaining: { fontFamily: 'Inter_700Bold', fontSize: 13, maxWidth: 95, textAlign: 'left' }, progressText: { flexDirection: 'row-reverse', justifyContent: 'space-between', marginTop: 9 }, tiny: { fontFamily: 'Inter_400Regular', fontSize: 11 }, pay: { fontFamily: 'Inter_700Bold', fontSize: 11 } });