import React from 'react';
import { Pressable, StyleSheet, Switch, Text, View } from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { Screen, AppHeader, IconBadge, SectionTitle } from '@/components/FinanceUI';
import { useFinance } from '@/store/FinanceContext';

export default function SettingsScreen() {
  const router = useRouter(); const { state, colors, isDark, setDarkMode, setCurrency } = useFinance();
  return <Screen><AppHeader title="الإعدادات" subtitle="خصّص تجربتك المالية" onBack={() => router.back()} /><SectionTitle title="المظهر" /><View style={[styles.setting, { backgroundColor: colors.card, borderColor: colors.border }]}><Switch value={isDark} onValueChange={setDarkMode} trackColor={{ false: colors.muted, true: colors.primary }} thumbColor={isDark ? colors.primaryForeground : '#FFFFFF'} /><View style={styles.info}><Text style={[styles.title, { color: colors.foreground }]}>الوضع الداكن</Text><Text style={[styles.subtitle, { color: colors.mutedForeground }]}>راحة أكبر للعين في الإضاءة المنخفضة</Text></View><IconBadge icon="weather-night" color="#5578C8" size={42} /></View><SectionTitle title="العملة" /><View style={[styles.currencyCard, { backgroundColor: colors.card, borderColor: colors.border }]}>{['ر.س', 'د.إ', '$', '€'].map(currency => <Pressable key={currency} onPress={() => setCurrency(currency)} style={[styles.currency, { backgroundColor: state.settings.currency === currency ? colors.primary : colors.secondary }]}><Text style={{ color: state.settings.currency === currency ? colors.primaryForeground : colors.secondaryForeground, fontFamily: 'Inter_700Bold', fontSize: 15 }}>{currency}</Text></Pressable>)}</View><SectionTitle title="حول التطبيق" /><View style={[styles.about, { backgroundColor: colors.secondary }]}><View style={styles.logo}><MaterialCommunityIcons name="shield-check-outline" size={28} color={colors.primary} /></View><Text style={[styles.appName, { color: colors.foreground }]}>Isnad Financial Manager</Text><Text style={[styles.aboutText, { color: colors.mutedForeground }]}>مديرك المالي الشخصي، يعمل دون إنترنت وبخصوصية كاملة.</Text><Text style={[styles.version, { color: colors.mutedForeground }]}>الإصدار 1.0.0 • سبع مجموعات بيانات محلية</Text></View><View style={[styles.privacy, { borderColor: colors.border }]}><MaterialCommunityIcons name="database-lock-outline" size={19} color={colors.primary} /><Text style={[styles.privacyText, { color: colors.mutedForeground }]}>لا نرسل بياناتك لأي خادم. التخزين محلي على جهازك.</Text></View></Screen>;
}
const styles = StyleSheet.create({ setting: { minHeight: 74, borderWidth: 1, borderRadius: 19, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', gap: 12 }, info: { flex: 1, alignItems: 'flex-end' }, title: { fontFamily: 'Inter_700Bold', fontSize: 14 }, subtitle: { fontFamily: 'Inter_400Regular', fontSize: 11, marginTop: 4, textAlign: 'right' }, currencyCard: { borderWidth: 1, borderRadius: 19, padding: 12, flexDirection: 'row-reverse', gap: 9 }, currency: { flex: 1, borderRadius: 13, height: 45, alignItems: 'center', justifyContent: 'center' }, about: { borderRadius: 21, padding: 21, alignItems: 'center' }, logo: { width: 58, height: 58, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: '#0C8F7420' }, appName: { fontFamily: 'Inter_700Bold', fontSize: 16, marginTop: 13 }, aboutText: { fontFamily: 'Inter_400Regular', fontSize: 12, marginTop: 7, textAlign: 'center' }, version: { fontFamily: 'Inter_400Regular', fontSize: 10, marginTop: 15 }, privacy: { flexDirection: 'row-reverse', alignItems: 'center', justifyContent: 'center', gap: 8, borderWidth: 1, borderRadius: 15, padding: 12, marginTop: 15 }, privacyText: { fontFamily: 'Inter_400Regular', fontSize: 11 } });