import React, { useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { Screen, AppHeader, FormModal, IconBadge, SectionTitle, EmptyState } from '@/components/FinanceUI';
import { formatMoney, useFinance } from '@/store/FinanceContext';

export default function AccountsScreen() {
  const { state, colors, addAccount } = useFinance();
  const [showForm, setShowForm] = useState(false);
  const currency = state.settings.currency;
  return <Screen><AppHeader title="الحسابات" subtitle={`${state.accounts.length} حسابات مالية`} action={() => setShowForm(true)} /><View style={[styles.total, { backgroundColor: colors.secondary }]}><View><Text style={[styles.totalLabel, { color: colors.secondaryForeground }]}>الرصيد الإجمالي</Text><Text style={[styles.totalValue, { color: colors.foreground }]}>{formatMoney(state.accounts.reduce((sum, a) => sum + a.openingBalance, 0), currency)}</Text></View><IconBadge icon="wallet-outline" color={colors.primary} size={48} /></View><SectionTitle title="حساباتي" />{state.accounts.length === 0 ? <EmptyState icon="wallet-outline" title="لا توجد حسابات" description="أضف حسابك النقدي أو البنكي للبدء." onPress={() => setShowForm(true)} action="إضافة حساب" /> : state.accounts.map(account => <View key={account.id} style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border }]}><IconBadge icon={account.type === 'bank' ? 'bank-outline' : account.type === 'savings' ? 'piggy-bank-outline' : account.type === 'card' ? 'credit-card-outline' : 'cash-multiple'} color={account.color} size={48} /><View style={styles.info}><Text style={[styles.name, { color: colors.foreground }]}>{account.name}</Text><Text style={[styles.type, { color: colors.mutedForeground }]}>{account.type === 'bank' ? 'حساب بنكي' : account.type === 'savings' ? 'حساب ادخار' : account.type === 'card' ? 'بطاقة' : 'نقدي'}</Text></View><Text style={[styles.amount, { color: colors.foreground }]}>{formatMoney(account.openingBalance, currency)}</Text></View>)}<FormModal visible={showForm} title="إضافة حساب" onClose={() => setShowForm(false)} onSubmit={values => addAccount({ name: values.name, type: values.type as 'cash' | 'bank' | 'card' | 'savings', openingBalance: Number(values.openingBalance), color: values.type === 'bank' ? '#5578C8' : values.type === 'savings' ? '#D98E3A' : colors.primary })} fields={[{ key: 'name', label: 'اسم الحساب', placeholder: 'مثال: حسابي البنكي' }, { key: 'type', label: 'نوع الحساب', choices: [{ label: 'نقدي', value: 'cash' }, { label: 'بنكي', value: 'bank' }, { label: 'ادخار', value: 'savings' }, { label: 'بطاقة', value: 'card' }] }, { key: 'openingBalance', label: 'الرصيد الافتتاحي', placeholder: '0', keyboardType: 'decimal-pad' }]} initialValues={{ type: 'cash' }} /></Screen>;
}
const styles = StyleSheet.create({ total: { borderRadius: 20, padding: 18, flexDirection: 'row-reverse', justifyContent: 'space-between', alignItems: 'center' }, totalLabel: { fontFamily: 'Inter_500Medium', fontSize: 12, textAlign: 'right' }, totalValue: { fontFamily: 'Inter_700Bold', fontSize: 23, marginTop: 6, textAlign: 'right' }, card: { minHeight: 77, borderWidth: 1, borderRadius: 20, marginBottom: 10, padding: 13, flexDirection: 'row-reverse', alignItems: 'center', gap: 11 }, info: { flex: 1, alignItems: 'flex-end' }, name: { fontFamily: 'Inter_700Bold', fontSize: 14 }, type: { fontFamily: 'Inter_400Regular', fontSize: 11, marginTop: 4 }, amount: { fontFamily: 'Inter_700Bold', fontSize: 13 } });